name: CI
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  ci-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - name: Configure Python
      run: |
        python3 -m venv py
        ./py/bin/python3 -m pip install setuptools wheel twine build
        sed -i -e pyproject.toml -e "s/version = \"([0-9][0-9]*.[0-9][0-9]*.[0-9][0-9]*\)\"/version = \"\1.${GITHUB_RUN_ID}\"/"
        ./py/bin/python3 -m build --wheel --no-isolation 
#    - name: Build Docs
#      run: |
#        make html
#        touch doc/build/html/.nojekyll
#        cp -r doc/build/html .
#    - name: Publish Docs
#      if: startsWith(github.ref, 'refs/heads/main')
#      uses: JamesIves/github-pages-deploy-action@4.1.7
#      with:
#        branch: gh-pages
#        folder: html
    - name: Publish to PyPi
      if: startsWith(github.ref, 'refs/heads/main')
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        ./py/bin/pyhon3 -m twine upload dist/*.whl

